version: '3.1'

services:

  wordpress:
    image: wordpress:6.2
    restart: always
    env_file: ./.env
    ports:
      - 4000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./data/wp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: wp_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 2s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - '4001:80'
    depends_on:
      - db
